services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./databases:/var/www/html
    networks:
      - default

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./databases:/var/www/html
      - ./databases/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - default
