version: '3.8'

services:
  mariadb:
    container_name: db
    image: mariadb:10.9.8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysqldata:/var/lib/mysql
    networks:
      - network

  php:
    container_name: php
    build:
      context: .
      dockerfile: php-dockerfile
    volumes:
      - ./api:/var/www/html
      - ./php-logging.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - network

  nginx:
    container_name: web
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./api:/var/www/html
      - ./api/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - network

  proxy:
    container_name: proxy
    image: node:14-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./proxy:/app
    working_dir: /app
    command: "node server.js"
    depends_on:
      - nginx
    networks:
      - network

networks:
  network:

